In [24]:
import os
import numpy as np 
import pandas as pd

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [26]:
df=pd.read_csv(r"C:\Users\mayur\OneDrive\Desktop\data science training\project\cutomer churn predition system\data\new.csv")

In [27]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineBackup,TechSupport,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,OnlineSecurity_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,DeviceProtection_No internet service,DeviceProtection_Yes
0,0,0,1,0,1,0,1,0,2,0,...,1,2,29.85,29.85,0,1,0,0,0,0
1,1,0,0,0,34,1,0,0,0,0,...,0,3,56.95,1889.50,0,0,0,1,0,1
2,1,0,0,0,2,1,0,0,2,0,...,1,3,53.85,108.15,1,0,0,1,0,0
3,1,0,0,0,45,0,1,0,0,2,...,0,0,42.30,1840.75,0,0,0,1,0,1
4,0,0,0,0,2,1,0,1,0,0,...,1,2,70.70,151.65,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,0,2,...,1,3,84.80,1990.50,0,0,0,1,0,1
7039,0,0,1,1,72,1,2,1,2,0,...,1,1,103.20,7362.90,0,1,0,0,0,1
7040,0,0,1,1,11,0,1,0,0,0,...,1,2,29.60,346.45,0,0,0,1,0,0
7041,1,1,1,0,4,1,2,1,0,0,...,1,3,74.40,306.60,1,1,0,0,0,0
7042,1,0,0,0,66,1,0,1,0,2,...,1,0,105.65,6844.50,0,0,0,1,0,1

In [28]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   gender                                7043 non-null   int64
 1   SeniorCitizen                         7043 non-null   int64
 2   Partner                               7043 non-null   int64
 3   Dependents                            7043 non-null   int64
 4   tenure                                7043 non-null   int64
 5   PhoneService                          7043 non-null   int64
 6   MultipleLines                         7043 non-null   int64
 7   InternetService                       7043 non-null   int64
 8   OnlineBackup                          7043 non-null   int64
 9   TechSupport                           7043 non-null   int64
 10  StreamingTV                           7043 non-null   int64
 11  StreamingMovies                       7043 non-null   int64
 12  Contract                              7043 non-null   int64
 13  PaperlessBilling                      7043 non-null   int64
 14  PaymentMethod                         7043 non-null   int64
 15  MonthlyCharges                        7043 non-null   float64
 16  TotalCharges                          7043 non-null   float64
 17  Churn                                 7043 non-null   int64
 18  OnlineSecurity_No                     7043 non-null   int64
 19  OnlineSecurity_No internet service    7043 non-null   int64
 20  OnlineSecurity_Yes                    7043 non-null   int64
 21  DeviceProtection_No internet service  7043 non-null   int64
 22  DeviceProtection_Yes                  7043 non-null   int64
dtypes: float64(2), int64(21)
memory usage: 1.2 MB
None

In [29]:
df.isnull().sum()

gender                                  0
SeniorCitizen                           0
Partner                                 0
Dependents                              0
tenure                                  0
PhoneService                            0
MultipleLines                           0
InternetService                         0
OnlineBackup                            0
TechSupport                             0
StreamingTV                             0
StreamingMovies                         0
Contract                                0
PaperlessBilling                        0
PaymentMethod                           0
MonthlyCharges                          0
TotalCharges                            0
Churn                                   0
OnlineSecurity_No                       0
OnlineSecurity_No internet service      0
OnlineSecurity_Yes                      0
DeviceProtection_No internet service    0
DeviceProtection_Yes                    0
dtype: int64

In [30]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [31]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineBackup,TechSupport,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,OnlineSecurity_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,DeviceProtection_No internet service,DeviceProtection_Yes
0,0,0,1,0,1,0,1,0,2,0,...,0,1,2,29.85,29.85,1,0,0,0,0
1,1,0,0,0,34,1,0,0,0,0,...,1,0,3,56.95,1889.50,0,0,1,0,1
2,1,0,0,0,2,1,0,0,2,0,...,0,1,3,53.85,108.15,0,0,1,0,0
3,1,0,0,0,45,0,1,0,0,2,...,1,0,0,42.30,1840.75,0,0,1,0,1
4,0,0,0,0,2,1,0,1,0,0,...,0,1,2,70.70,151.65,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,0,2,...,1,1,3,84.80,1990.50,0,0,1,0,1
7039,0,0,1,1,72,1,2,1,2,0,...,1,1,1,103.20,7362.90,1,0,0,0,1
7040,0,0,1,1,11,0,1,0,0,0,...,0,1,2,29.60,346.45,0,0,1,0,0
7041,1,1,1,0,4,1,2,1,0,0,...,0,1,3,74.40,306.60,1,0,0,0,0
7042,1,0,0,0,66,1,0,1,0,2,...,2,1,0,105.65,6844.50,0,0,1,0,1

In [32]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
log=LogisticRegression()
log.fit(X_train,y_train)
print("log training",log.score(X_train,y_train))
print("log testing",log.score(X_test,y_test))

log training 0.8015619453319134
log testing 0.7977288857345636

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [36]:
import joblib

joblib.dump(log, "log_model.lb")

['log_model.lb']

In [37]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
print("dt training",dt.score(X_train,y_train))
print("dt testing",dt.score(X_test,y_test))

dt training 0.9980475683351083
dt testing 0.7281760113555713

In [38]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(X_train,y_train)
print("svc training",sv.score(X_train,y_train))
print("svc testing",sv.score(X_test,y_test))

svc training 0.7346467873624423
svc testing 0.7345635202271115

In [39]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

print("RF Training :", rf.score(X_train, y_train))
print("RF Testing  :", rf.score(X_test, y_test))

RF Training : 0.9980475683351083
RF Testing  : 0.7856635911994322

In [40]:
from sklearn.metrics import classification_report

y_pred = log.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.64      0.56      0.59       374

    accuracy                           0.80      1409
   macro avg       0.74      0.72      0.73      1409
weighted avg       0.79      0.80      0.79      1409

In [41]:
print(df.head())

   gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0
1       1              0        0           0      34             1
2       1              0        0           0       2             1
3       1              0        0           0      45             0
4       0              0        0           0       2             1

   MultipleLines  InternetService  OnlineBackup  TechSupport  ...  \
0              1                0             2            0  ...
1              0                0             0            0  ...
2              0                0             2            0  ...
3              1                0             0            2  ...
4              0                1             0            0  ...

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  \
0                 1              2           29.85         29.85      0
1                 0              3           56.95       1889.50      0
2                 1              3           53.85        108.15      1
3                 0              0           42.30       1840.75      0
4                 1              2           70.70        151.65      1

   OnlineSecurity_No  OnlineSecurity_No internet service  OnlineSecurity_Yes  \
0                  1                                   0                   0
1                  0                                   0                   1
2                  0                                   0                   1
3                  0                                   0                   1
4                  1                                   0                   0

   DeviceProtection_No internet service  DeviceProtection_Yes
0                                     0                     0
1                                     0                     1
2                                     0                     0
3                                     0                     1
4                                     0                     0

[5 rows x 23 columns]

In [42]:
print(df.dtypes)

gender                                    int64
SeniorCitizen                             int64
Partner                                   int64
Dependents                                int64
tenure                                    int64
PhoneService                              int64
MultipleLines                             int64
InternetService                           int64
OnlineBackup                              int64
TechSupport                               int64
StreamingTV                               int64
StreamingMovies                           int64
Contract                                  int64
PaperlessBilling                          int64
PaymentMethod                             int64
MonthlyCharges                          float64
TotalCharges                            float64
Churn                                     int64
OnlineSecurity_No                         int64
OnlineSecurity_No internet service        int64
OnlineSecurity_Yes                        int64
DeviceProtection_No internet service      int64
DeviceProtection_Yes                      int64
dtype: object

In [43]:
print(X.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineBackup', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'OnlineSecurity_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes']

In [45]:
import joblib

# X = your training features
joblib.dump(X.columns, r"C:\Users\mayur\OneDrive\Desktop\data science training\project\cutomer churn predition system\model/columns.lb")

['C:\\Users\\mayur\\OneDrive\\Desktop\\data science training\\project\\cutomer churn predition system\\model/columns.lb']